name: CI workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      container: python:3.9-slim
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Lint code
          run: 
            pip install flake8
            flake8
        - name: Run install nose
          run: 
            pip install nose
        - name: RUn unit test with nose
          run: nosetests
